### ISSUE TITLE
cannot open URL

### ISSUE THREAD

**Issue by LinacRT** [muschellij2/itksnapr#5]
I am trying to install the itksnapr library and i can see it in my list of packages but this is the error message when trying to use the library: Error in download.file(url, destfile, quiet = TRUE) : 
  cannot open URL 'https://github.com/muschellij2/itksnapr/raw/gh-pages/darwin-aarch64.zip'

(i have tried installing via devtools and the error is constant). I am using R 4.3.3. Appreciate the help!

**Comment by muschellij2** [comment]
Can you try now?

**Comment by LinacRT** [comment]
Hi, thanks so much. Still stuck on the same problem unfortunately. I am going to try to use another version of R and see if that works as it seems to work for a colleague on R 4.0.5

**Comment by muschellij2** [comment]
Did you reinstall from github?

Best,
John

**Comment by LinacRT** [comment]
Hi John, I did reinstall from Github and every other package seems to be working fine so its a bit odd. This is the error message now: 
Error in download.file(url, destfile, quiet = TRUE) : 
  cannot open URL 'https://raw.githubusercontent.com/muschellij2/itksnapr/gh-pages/darwin-aarch64.zip'
In addition: Warning messages:
1: In download.file(url, destfile, quiet = TRUE) :
  downloaded length 0 != reported length 14
2: In download.file(url, destfile, quiet = TRUE) :
  cannot open URL 'https://raw.githubusercontent.com/muschellij2/itksnapr/gh-pages/darwin-aarch64.zip': HTTP status was '404 Not Found'

**Comment by muschellij2** [comment]
https://stackoverflow.com/help/minimal-reproducible-example
